# Random

In [14]:
import numpy as np
import random

## Setting a seed for reproducability

In [2]:
np.random.seed(123)

## Choosing a random item from a list

In [24]:
random.choice([5, 10, 15])

5

## Generate a random number between 0 and 1

In [3]:
np.random.rand()

0.6964691855978616

In [4]:
np.random.random()

0.28613933495037946

## Generate a random integer between 0 and 10

In [7]:
np.random.randint(0, 11, size=5)

array([4, 3, 3, 7, 6])

## Generate a 2d array of random integers

In [9]:
np.random.randint(1, 100, size=(10, 2))

array([[89, 71],
       [14, 29],
       [64, 85],
       [37, 97],
       [41, 89],
       [64, 59],
       [78,  9],
       [79,  7],
       [66, 95],
       [71, 41]])

## Generate random numbers from a normal distribution

In [11]:
np.random.normal(size=5)

array([ 1.05828038, -0.54181905,  2.57177461,  1.34761572,  0.25894582])

### We can specify the mean with loc and standard deviation with scale

In [12]:
returns = np.random.normal(loc=0.02, scale=0.05, size=1000)

mean = np.mean(returns)
std = np.std(returns)
print("The mean is %5.3f and the standard deviation is %5.3f" %(mean, std))

The mean is 0.022 and the standard deviation is 0.052
