# Random

In [84]:
import numpy as np
import random
from scipy.stats import uniform

## Setting a seed for reproducability

In [85]:
np.random.seed(123)

## Choosing a random item from a list

In [86]:
items = list(range(20))

### Chosing 1 random number

In [87]:
np.random.choice(items)

13

### Choosing multiple random numbers with replacement

In [88]:
np.random.choice(items, 10)

array([ 2,  2,  6, 17, 19, 10,  1,  0, 17, 15])

### Choosing multiple random numbers without replacement

In [97]:
np.random.choice(items, 10, replace=False)

array([18, 11,  3, 19, 14, 17,  1, 12, 15, 10])

In [101]:
random.sample(items, 10)

[12, 17, 16, 6, 11, 10, 1, 5, 18, 14]

## Generate a random number between 0 and 1

In [89]:
np.random.rand()

0.3921175181941505

In [90]:
np.random.random()

0.3431780161508694

In [91]:
uniform().rvs(1)[0]

0.7290497073840416

## Generate a random integer between 0 and 10

In [92]:
np.random.randint(0, 11, size=5)

array([3, 4, 0, 0, 4])

## Generate a 2d array of random integers

In [93]:
np.random.randint(1, 100, size=(10, 2))

array([[50, 56],
       [68,  3],
       [85, 40],
       [67, 85],
       [48, 62],
       [49,  8],
       [93, 53],
       [98, 86],
       [95, 28],
       [35, 98]])

## Generate random numbers from a normal distribution

In [94]:
np.random.normal(size=5)

array([-0.32694623, -0.3082092 ,  0.82711746,  1.07078142, -3.05557742])

### We can specify the mean with loc and standard deviation with scale

In [95]:
# loc is the mean
# scale is the standard deviation
returns = np.random.normal(loc=0.02, scale=0.05, size=1000)

mean = np.mean(returns)
std = np.std(returns)
print("The mean is %5.3f and the standard deviation is %5.3f" %(mean, std))

The mean is 0.021 and the standard deviation is 0.054


### Also possible using scipy's uniform function

In [96]:
returns = uniform().rvs(1000)

mean = np.mean(returns)
std = np.std(returns)
print("The mean is %5.3f and the standard deviation is %5.3f" %(mean, std))

The mean is 0.504 and the standard deviation is 0.292
